params:
  cpn27:
    n_dim: 1200
    random_state: 0
  cpn120:
    n_dim: 1780
    random_state: 0

enviroment:
  nlp: es_core_news_sm
  language: spanish

path_data:
  cpn120: ../data/raw_dataset/CPN120.csv
  cpn27: ../data/raw_dataset/CPN27.csv


