params:
  random_state: 0
  
  cpn27:
    n_dim: 1200

  cpn120:
    n_dim: 1780

enviroment:
  nlp: es_core_news_sm
  language: spanish

path_data:
  cpn120: ../data/raw_dataset/CPN120.csv
  cpn27: ../data/raw_dataset/CPN27.csv

path_results:
  grafics: ../data/results/LSA/Graphics/

